version: '3.8'
services:
  app:
    container_name: ${PROJECT_NAME}-API
    build: 
      context: .
      dockerfile: /php/Dockerfile
    depends_on:
      - db
    volumes:
      - ..:/var/www/html/
    ports:
      - ${APACHE_PORT}:80
  db:
    container_name: ${PROJECT_NAME}-DB
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_USER}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: ${PROJECT_NAME}-PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    ports:
        - ${PHPMYADMIN_PORT}:80
    restart: always
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 1G
        MAX_EXECUTION_TIME: 6000
    depends_on:
        - db

volumes:
  db-data:
    name: ${PROJECT_NAME}-vol
    external: true

